<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../ScalabilityMeasurement.cs" Link="ScalabilityMeasurement.cs" />
    <ProjectReference Include="../../src/ForgeLine.Client/ForgeLine.Client.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="../../src/ForgeLine.Graphics/ForgeLine.Graphics.csproj" />
    <ProjectReference Include="../../src/ForgeLine.Presentation/ForgeLine.Presentation.csproj" />
    <ProjectReference Include="../../src/ForgeLine.World/ForgeLine.World.csproj" />
  </ItemGroup>
</Project>
