namespace ForgeLine.Input;

/// <summary>Current English fallback templates. Cached key substitution shares the command registry without frame-time formatting.</summary>
internal static class GameplayPromptCatalog
{
    internal static readonly string[] English =
    [
        "3 BUILD POWER AND INDUSTRY WITH B",
        "4 PROCESS MATERIALS WITH P AND PRODUCE UNITS WITH U",
        "5 USE L AND Y TO KEEP THE FRONT SUPPLIED",
        "6 USE K FOR ATTACK ATTACK-MOVE RETREAT AND ARTILLERY",
        "B BUILD  P PROCESS  U UNITS  L LOGISTICS  Y SUPPLY",
        "B BUILD / COMMAND CORE",
        "B BUILD / MINE / EXTRACTOR",
        "B BUILD / POWER PLANT",
        "B BUILD / VEHICLE FACTORY",
        "CHOOSE ANOTHER LOCATION / F9 ROTATE",
        "CLICK OR K / TAB / ENTER; WATCH COMMAND FEEDBACK",
        "DELIVER INPUTS WITH CARGO / L LOGISTICS",
        "ENTER START  ESC EXIT",
        "ENTER START MATCH",
        "ESC OR SPACE PAUSE  SHIFT+F1 METRICS  F2 WORLD DEBUG",
        "ESC OR SPACE PAUSE MENU",
        "ESC OR SPACE RESUME",
        "F10 LAYERS F11 MINIMAP",
        "F10 STRATEGIC OVERLAY  F11 MINIMAP  F1/F12/ESC CLOSE HELP",
        "F4 COMMAND CORE  F5 POWER PLANT  F6 EXTRACTOR",
        "F7 STORAGE DEPOT  F8 SMELTER  F9 ROTATE BUILDING",
        "H TECHNOLOGY / CHECK THE REQUIRED UNLOCK",
        "HOME BASE  F1 HELP  SPACE PAUSE  SHIFT+F12 GUIDE",
        "HOME BASE FOCUS  CTRL+DIGIT ASSIGN  DOUBLE DIGIT GROUP FOCUS",
        "K COMBAT / F1 HELP",
        "L LOGISTICS  Y SUPPLY  K COMBAT",
        "L LOGISTICS / SELECT FACTORY / U UNITS",
        "L LOGISTICS / SELECT SMELTER / P PROCESS",
        "L LOGISTICS / Y SUPPLY",
        "LEFT CLICK REQUEST / ESC CANCEL / F9 ROTATE",
        "MOVE OUTPUT TO STORAGE / L LOGISTICS",
        "RIGHT CLICK MOVE  B BUILD  P PROCESS  U UNITS",
        "RIGHT CLICK MOVE  K COMBAT  H TECHNOLOGY",
        "RIGHT CLICK MOVE / F11 MINIMAP",
        "SELECT CARD / ENTER TO ACT",
        "SHIFT+CLICK REPEAT BUILD AFTER ACCEPTANCE  F9 ROTATE  ESC CANCEL",
        "SHIFT+F1 PERFORMANCE METRICS  F2 WORLD DEBUG  F3 FORMATION"
    ];
}
